variables_dict = {
    # 3d quantities
    'e':            {'unit': 'm²/s²',   'description': 'SGS turbulence kinetic energy'},
    'hr':           {'unit': 'K/s',     'description': 'Heating rate'},
    'm_soil':       {'unit': 'm³/m³',   'description': 'Volumetric soil moisture'},
    'p':            {'unit': 'Pa',      'description': 'Perturbation pressure'},
    'pcm_heatrate': {'unit': 'K/s',     'description': 'Plant canopy heating rate by solar radiation'},
    'pcm_lad':      {'unit': 'm²/m³',   'description': 'Leaf area density'},
    'rad_lw_cs_hr': {'unit': 'K/h',     'description': 'Clear-sky longwave radiative heating rate'},
    'rad_lw_hr':    {'unit': 'K/h',     'description': 'Longwave radiative heating rate'},
    'rad_lw_in':    {'unit': 'W/m²',    'description': 'Incoming longwave radiation flux'},
    'rad_lw_out':   {'unit': 'W/m²',    'description': 'Outgoing longwave radiation flux'},
    'rad_sw_cs_hr': {'unit': 'K/h',     'description': 'Clear-sky shortwave radiative heating rate'},
    'rad_sw_hr':    {'unit': 'K/h',     'description': 'Shortwave radiative heating rate'},
    'rad_sw_in':    {'unit': 'W/m²',    'description': 'Incoming shortwave radiation flux'},
    'rad_sw_out':   {'unit': 'W/m²',    'description': 'Outgoing shortwave radiation flux'},
    'rh':           {'unit': '%',       'description': 'Relative humidity'},
    'rtm_mrt':      {'unit': 'K',       'description': 'Mean radiant temperature'},
    'rtm_mrt_lw':   {'unit': 'W/m²',    'description': 'LW fraction of MRT radiation flux'},
    'rtm_mrt_sw':   {'unit': 'W/m²',    'description': 'SW fraction of MRT radiation flux'},
    't_soil':       {'unit': 'K',       'description': 'Soil temperature'},
    'ta':           {'unit': '°C',      'description': 'True air temperature'},
    'theta':        {'unit': 'K',       'description': 'Potential temperature'},
    'thetal':       {'unit': 'K',       'description': 'Liquid water potential temperature'},
    'thetav':       {'unit': 'K',       'description': 'Virtual potential temperature'},
    'ti':           {'unit': 's⁻¹',     'description': 'Curl of velocity vector (magnitude)'},
    'u':            {'unit': 'm/s',     'description': 'U-component of velocity vector'},
    'v':            {'unit': 'm/s',     'description': 'V-component of velocity vector'},
    'w':            {'unit': 'm/s',     'description': 'W-component of velocity vector'},
    'wdir':         {'unit': 'degree',  'description': 'Direction of horizontal wind vector'},
    'wspeed':       {'unit': 'm/s',     'description': 'Magnitude of the horizontal wind vector'},
    
    # 2d quantities
    'rad_lw_in*':   {'unit': 'W/m²',    'description': 'incoming Lw radiation flux'},
    'rad_lw_out*':  {'unit': 'W/m²',    'description': 'outgoing Lw radiation flux'},
    'rad_sw_in*':   {'unit': 'W/m²',    'description': 'incoming Sw radiation flux'},
    'rad_sw_out*':  {'unit': 'W/m²',    'description': 'outgoing Sw radiation flux'},
    'rad_net*':     {'unit': 'W/m²',    'description': 'net radiation flux at surface'},
    'r_a*':         {'unit': 's/m',     'description': 'aerodynamic resistance'},
    't*':           {'unit': 'K',       'description': 'characteristic temperature'},
    'ta_2m*':       {'unit': '°C',      'description': '2-m air temperature'},
    'theta_2m*':    {'unit': 'K',       'description': '2-m potential temperature'},
    'tsurf*':       {'unit': 'K',       'description': 'surface temperature'},
    'wspeed_10m*':  {'unit': 'm/s',     'description': '10-m wind speed'},
    'bio_perct*':   {'unit': '°C',      'description': 'Perceived Temperature'},
    'bio_pet*':     {'unit': '°C',      'description': 'Physiologically Equivalent Temperature (PET)'},
    'bio_utci*':    {'unit': '°C',      'description': 'Universal Thermal Climate Index (UTCI)'},
    'us*':          {'unit': 'm/s',     'description': '(near surface) friction veloctiry'},
    
}